### ISSUE TITLE
Question freebox player.

### ISSUE THREAD

**Issue by landaisbenj** [SNoof85/freebox_custom-component#3]
Bonjour.

Je decouvre un peu HA, et je me demandais pourquoi il n'y avait pas d'integration du player de la revolution en temps que media_player ... On pourrait demander une source genre tele, replay etc... avec l'api dédié au player.. 
C'est juste une hypothese pour qui peut se le permettre. 

A part ca, j'utilise aussi avec domoticz de quoi ouvrir ou fermer un port routé sur la freebox. Il serait facile d'integrer une option pour switcher l'activation ou non d'un port (ex 443 vers 8123 sur HA) ce qui permet de verouiller l'acces a distance de HA si besoin.

Et sinon merci d'avoir integré la freebox (je n'ai pas encore testé).

**Comment by SNoof85** [comment]
Salut,

Je vais reprendre points par points : 
* API Player : c'est pas une volonté de pas l'intégrer mais la librairie aiofreepybox ne supporte pas (encore) l'API Player. C'est en cours de développement mais ça prends du temps !
* Pour les ouvertures / fermetures de ports j'ai déjà mis ça en place chez moi à un moment, je vais pouvoir le remettre dans ce custom component (je n'y avais pas pensé en fait !) Bon c'était pas hyper bien fichu parce que je devais restart HA pour qu'il voit les nouvelles règles ou qu'il supprime les règles qui ont été virées de la Freebox. Mais je dois pouvoir rendre ça plus dynamique.
Par contre, verrouiller l'accès à HA à distance c'est cool mais après ? Comment tu le remets à part par l'interface de la freebox ? Parce que faut savoir que l'API est "attaquée" par l'extérieur (même si HA est en LAN), c'est une volonté de dev Freebox d'avoir créé ça comme ça...

**Comment by landaisbenj** [comment]
Ok. 

Je ne suis pas trop au fait de ha pour le moment. Je ne comprends pas encore python. Sur domoticz, le player n’étais pas intégré, mais je me suis fait un petit script pour récupérer les commandes via ifttt sur gh afin que le player réagisse. Je pense faire pareil sur ha en attendant. Mais techniquement je ne savais pas qu’il fallait s’appuyer sur une librairie. Ça me rappel qui il a un code déjà développé pour le ifttt en concordance avec une application sur le player. Assistant freebox je crois. 

Pour les ports (l’idée de base) c’était de les fermer ou ouvrir automatiquement suivant la présence à la maison. Mais bon avec gh c’est un peu caduque sauf pour d’autre projet de la maison. Imaginons tu as plusieurs raspberry, tu peux automatiser l’ouverture de leur port...
